# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth12',
            field=models.CharField(max_length=20),
        ),
    ]
